### PR TITLE
Detect adjacent siblings & confirm that new child overlaps correctly …

### PR DESCRIPTION
**Pull request by mitchelljustin**
…with them

### CODE REVIEW

**Review by geralddejong — APPROVED** [review]
Suppose that there is a long series of hexalots coming in which is shaped like a circle and eventually overlaps itself.  Would that be detected?  (It may be necessary to search through all existing hexalots to really find a neighbor)

**Comment by mitchelljustin** [comment]
@geralddejong  What do you mean "a long series of hexalots coming in which is shaped like a circle"?

**Comment by geralddejong** [comment]
Suppose two series of hexalots go out in separate directions and then reconverge further out somewhere. They may not fail to overlap properly, despite the lack of "proximity" via the parent-child relationships.

**Comment by mitchelljustin** [comment]
The issue you pointed out invalidates this PR, so I'm closing it

**Pull request closed without merging**
